---
- hosts: webservers
  become: true
  tasks:

    - name: Install LAMP Packages
      apt: 
        name: "{{ item }}" 
        update_cache: yes 
        state: latest
      loop: [ 'apache2', 'mysql-server', 'python3-pymysql', 'php', 'php-mysql', 'libapache2-mod-php' ]     
             
    - name: Install PHP Add-ons
      apt: 
        name: "{{ item }}" 
        update_cache: yes 
        state: latest
      loop: [ 'php-curl', 'php-gd', 'php-mbstring', 'php-xml', 'php-xmlrpc', 'php-soap', 'php-intl', 'php-zip' ]     

    - name: Create the root account/password
      mysql_user:
        name: root
        password: "testing"
        login_unix_socket: /var/run/mysqld/mysqld.sock
  
    - name: Configure SQL DB for WordPress
      mysql_db:
        name: "Wordpress"
        state: present
        login_user: root
        login_password: "testing"
      
    - name: Create directory for domain to host Wordpress
      file:
        path: "/var/www/testwordpress"
        state: directory
        owner: "www-data"
        group: "www-data"
        mode: '0755'
      
    - name: Set up Apache VirtualHost
      template:
        src: "files/apache.conf.j2"
        dest: "/etc/apache2/sites-available/testwordpress.conf"
             
    - name: Enable new site
      shell: /usr/sbin/a2ensite testwordpress.conf
      
    - name: Disable default Apache site
      shell: /usr/sbin/a2dissite 000-default.conf
 
    - name: Enable rewrite module
      shell: /usr/sbin/a2enmod rewrite
           
    - name: Restart Apache to save configuration changes
      service:
        name: apache2
        state: restarted

    - name: "Allow HTTP on port 80"
      ufw:
        rule: allow
        port: "80"
        proto: tcp

    - name: Download and unpack latest WordPress
      unarchive:
        src: https://wordpress.org/latest.tar.gz
        dest: "/var/www/testwordpress"
        remote_src: yes
        creates: "/var/www/testwordpress/wordpress"
      
    - name: Set ownership for the untarred Wordpress files
      file:
        path: "/var/www/testwordpress"
        state: directory
        recurse: yes
        owner: www-data
        group: www-data
      
    - name: Set permissions for Wordpress directories
      shell: "/usr/bin/find /var/www/testwordpress/wordpress/ -type d -exec chmod 750 {} \\;"
      
    - name: Set permissions for Wordpress files
      shell: "/usr/bin/find /var/www/testwordpress/wordpress/ -type f -exec chmod 640 {} \\;"
      
    - name: Push wp-config
      template:
        src: "files/wp-config.php.j2"
        dest: "/var/www/testwordpress/wordpress/wp-config.php"
